{% set name = "sphinx-subfigure" %}
{% set version = "0.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sphinx_subfigure-{{ version }}.tar.gz
  sha256: d106193d0076bf29bb9594dbda23d3c13e9b2490e4344bc8018b6059a195de3b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - flit-core >=3.4,<4
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - sphinx

test:
  imports:
    - sphinx_subfigure
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/chrisjsewell/sphinx-subfigure
  summary: A sphinx extension to create sub-figures.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - chrisjsewell
